config/routes.rb
Rails.application.routes.draw do
  root 'messages#index'
  resources :messages do
    resources :likes, only: [:create]
  end

  delete 'message/:message_id', to: "likes#destroy", as: "unlike"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  after_create_commit { broadcast_append_later_to "thing", target: "message-container", partial: "messages/message" }
  after_update_commit { broadcast_replace_later_to "thing" }
  after_destroy_commit { broadcast_remove_to "thing" }

  validates :content, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  before_action :set_message

  def create
    @message.update!(liked: true)
    redirect_to @message
  end

  def destroy
    @message.update!(liked: false)
    redirect_to @message
  end

  private

    def set_message
      @message = Message.find(params[:message_id])
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: %i[ show edit update destroy ]

  # GET /messages or /messages.json
  def index
    @message = Message.new
    @messages = Message.all
  end

  # GET /messages/1 or /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages or /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to messages_url, notice: "Message was successfully created." }
        format.json { render :show, status: :created, location: @message }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@message, partial: "messages/form", locals: { message: @message }) }
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1 or /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: "Message was successfully updated." }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1 or /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: "Message was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def message_params
      params.require(:message).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="has-background-light">
  <head>
    <title>TurboPractice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="has-background-light">
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_with(model: message, id: dom_id(message)) do |form| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% message.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="is-flex is-justify-content-space-between">
    <div class="field is-flex-grow-1 mr-3">
      <%= form.text_field :content, class: "input", placeholder: "Type your message here", autofocus: true %>
    </div>
    <div class="is-flex-grow-0">
      <% if message.new_record? %>
        <%= form.submit "Send", class: "button" %>
      <% else %>
        <%= link_to "Cancel", root_path, class: "button is-danger is-light", "data-turbo_frame": "_top"  %>
        <%= form.submit "Update", class: "button is-success is-light" %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/messages/_message.html.erb
<%= turbo_frame_tag dom_id(message) do %>
  <div class="notification is-link m-3">
    <div class="level">
      <div class="level-left">
        <div class="level-item">
          <%= message.content %>
        </div>
      </div>
      <div class="level-right">
        <div class="level-item">
          <% if message.liked %>
            <%= button_to "👍", unlike_path(message), class: "button is-light", method: :delete %>
          <% else %>
            <%= button_to "👊", message_likes_path(message), class: "button is-info" %>
          <% end %>
        </div>
        <div class="level-item">
          <%= link_to "🗒️", edit_message_path(message), class: "button is-info" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= turbo_frame_tag dom_id(@message) do %>
  <%= render 'form', message: @message %>
<% end %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<%= turbo_stream_from :thing %>

<section class="section">
  <h1 class="title">Messages</h1>

  <div class="box mb-3">
    <%= turbo_frame_tag "message-container" do %>
      <%= render @messages %>
    <% end %>
  </div>
  
  <%= turbo_frame_tag "new_message_form" do %>
    <%= render 'messages/form', message: @message %>
  <% end %>
</section>

app/views/messages/new.html.erb
<%= turbo_frame_tag "new_message" do %>
  <h1>New Message</h1>

  <%= render 'form', message: @message %>

  <%= link_to 'Back', messages_path %>
<% end %>

app/views/messages/show.html.erb
<%= render partial: "message", locals: { message: @message } %>